name: Build

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: 'recursive'

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@main

      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main

      - name: Setup golang
        uses: actions/setup-go@main
        with:
           go-version: 'stable'

      - name: Setup gomobile
        shell: bash
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: app
          path: app/build/outputs/apk/*
